package binTemplate

var headerTpl = `// Code generated by genbin. DO NOT EDIT.
package {{.Package}}

import (
    "bytes"
    . "encoding/binary"
{{- range .Imports }}
    "{{$.Package}}/{{.}}"
{{- end}}
)

`

func init() {
    Register("header", headerTpl)
}
